### ISSUE TITLE
Error: ENOENT: no such file or directory when trying to generate

### ISSUE THREAD

**Issue by cabraviva** [micalevisk/ssh-keygen-lite#5]
I'm trying to generate a SSH Keypair, but keep getting this error:
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'C:\Users\user\Documents\code\quickssh\.quicksshinternal\hostkey'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\user\\Documents\\code\\quickssh\\.quicksshinternal\\hostkey'
}
```

My code:
```js
// internaldir is the path to a folder (C:\\Users\\user\\Documents\\code\\quickssh\\.quicksshinternal)

const keyPair = await keygen({
        location: path.join(internaldir, 'hostkey'),
        comment: 'Host key for QuickSSH',
        format: 'PEM',
        read: true,
        password: '',
        size: '2048',
        destroy: true,
        force: true
})
```

**Comment by micalevisk** [comment]
Hi! does the code below return `true`  
`console.log( fs.existsSync(path.join(internaldir, 'hostkey')) )`

**Comment by micalevisk** [comment]
also, can you please run with `process.env.VERBOSE='true'`? then you'll see a bunch of debugging logs generated by the lib

**Comment by cabraviva** [comment]
Hey, the output is:
```js
console.log( fs.existsSync(path.join(internaldir, 'hostkey')) ) // => false
    const keyPair = await keygen({
        location: path.join(internaldir, 'hostkey'),
        comment: 'Host key for QuickSSH',
        format: 'PEM',
        read: true,
        password: '',
        size: '2048',
        destroy: true,
        force: true
    })
    console.log( fs.existsSync(path.join(internaldir, 'hostkey')) ) // => Doesn't even get that far
```

And if I trie to create that file:
```js
if (!fs.existsSync(path.join(internaldir, 'hostkey'))) fs.writeFileSync(path.join(internaldir, 'hostkey'), '')
    console.log( fs.existsSync(path.join(internaldir, 'hostkey')) ) // => true
    const keyPair = await keygen({
        location: path.join(internaldir, 'hostkey'),
        comment: 'Host key for QuickSSH',
        format: 'PEM',
        read: true,
        password: '',
        size: '2048',
        destroy: true,
        force: true
    })
```
its created but deleted right after.

If I use this code:
```js
process.env.VERBOSE='true'

    if (!fs.existsSync(path.join(internaldir, 'hostkey'))) fs.writeFileSync(path.join(internaldir, 'hostkey'), '')

    const keyPair = await keygen({
        location: path.join(internaldir, 'hostkey'),
        comment: 'Host key for QuickSSH',
        format: 'PEM',
        read: true,
        password: '',
        size: '2048',
        destroy: true,
        force: true
    })
```
I just get the same output

**Comment by micalevisk** [comment]
alright. The file you pass to `location` doesn't need to exist beforehand but the directory it leaves should be. Does `existsSync(path.join(internaldir)) === true`?

Also, that env `VERBOSE='true'` won't work if you've loaded the package before because the logger is initialized when you call `require('ssh-keygen-lite')`

**Comment by cabraviva** [comment]
This is my output with VERBOSE set to true:
```
Exist Status of internaldir: true
ssh-keygen: checking availability: C:\Users\user\Documents\code\quickssh\.quicksshinternal\hostkey
ssh-keygen: checking availability: C:\Users\user\Documents\code\quickssh\.quicksshinternal\hostkey.pub
ssh-keygen: exited with code:3221225781
ssh-keygen: reading file C:\Users\user\Documents\code\quickssh\.quicksshinternal\hostkey
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'C:\Users\user\Documents\code\quickssh\.quicksshinternal\hostkey'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\user\\Documents\\code\\quickssh\\.quicksshinternal\\hostkey'
}
```

**Comment by micalevisk** [comment]
yeah, I believe it shouldn't be running after `ssh-keygen` exiting with a non-zero code.

Does the directory `C:\Users\user\Documents\code\quickssh\.quicksshinternal` exists?

**Comment by cabraviva** [comment]
Yes it does, here's the file structure
![image](https://user-images.githubusercontent.com/64889695/167213348-6a265123-4c02-4fbc-926b-774eeff8265f.png)
(The other files are generated by other parts of my code)

**Comment by micalevisk** [comment]
I'll release a new patch that will break the flow if `ssh-keygen` exits with something other than `0`. So it won't work in your machine anymore. You'll need to see what that code `3221225781` means to `ssh-keygen` :/

A couldn't reproduce this here

**Comment by cabraviva** [comment]
I did some research and I think I need to install C++ Build Tools or something. I'll close this issue if this fixed it

**Comment by micalevisk** [comment]
can you check how it behaves now? you should get an error as string telling that `ssh-keygen` exits with that code

**Comment by cabraviva** [comment]
I get an error:
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "ssh-keygen exited with code: 3221225781".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

Also, I took a quick look at your code and saw that you're using `ssh-keygen` on linux and some binaries on windows. Windows also supports the `ssh-keygen` command, which works for me, so you might just try to use `ssh-keygen` on windows too.

**Comment by micalevisk** [comment]
add some error handling like `.catch(console.error)`

**Comment by micalevisk** [comment]
> so you might just try to use ssh-keygen on windows too.

I didn't have a Windows machine to test it out. Feel free to open a PR to change that `binPath` function to check if the `ssh-keygen` is available before falling back to those binaries.

**Comment by cabraviva** [comment]
Ok, I opened #6

**Comment by cabraviva** [comment]
I could verify that this works on windows too now
